# Site settings
name: Anhtram Nguyen
email: anhtram.nguyen@gmail.com
#url: https://anhtramnguyen.com
keywords: "Software Engineer, Python, Ruby, Machine Learning, Deep Learning, Startups, Agile, Pair Programming"
skills: "Senior Software Engineer in New York"
meta_author: Anhtram Nguyen

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/anhtramnguyen/

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1

# Footer settings
footer:
  copyright: Anhtram Nguyen
  location:
  social: Around the Web
  credits:


# Build settings
markdown: kramdown
permalink: pretty
